CREATE TABLE system_metadata (
  metadata_key VARCHAR(128) NOT NULL PRIMARY KEY,
  metadata_value VARCHAR(512) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB;
