CREATE TABLE users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  openid_hash BINARY(32) NOT NULL,
  timezone VARCHAR(64) NOT NULL DEFAULT 'UTC',
  large_text_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  high_contrast_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_users_openid_hash (openid_hash)
) ENGINE=InnoDB;
